timesheet:
    - account: ENC[AES256_GCM,data:axxfTA==,iv:5548P08OzdZc8NnBsUrA5gEmbWigNyKtpOYg2R4sx0U=,tag:7mnRr0hoOAXD4SPT66N3CQ==,type:str]
      path: ENC[AES256_GCM,data:gwFCT175+nf9Ia/GPsW1JJ2TbludbVwId7GeqA1u90FeviOnXfRigVxdvzuPMBC6jA==,iv:a6M/gYAidz41SYEKVmo72SFEf0oUqsK7FGhDAThYU9c=,tag:EGXxnZ7t+Yd9B+czVWiLmg==,type:str]
      mode: ENC[AES256_GCM,data:O9GjMBqmvpNrm9WAaA==,iv:7wU2uh2z5y39j389XpDPnZ6qkVr811lc+LB05JRSzyI=,tag:hNLwjOA97pLRnH5ognoMzQ==,type:str]
sops:
    age:
        - recipient: age1m954z8ajdedsmvr9u89ud5v2zednmxgvvzuahpfy5fcdp97yn99ssy2wmm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OUl4OGZiWGt4V095VUpN
            ZW9ZN3Nqd2U5amdENTlCZG1sMkYwZmRkbFdrCktJYUR5b3BTM0hhb1E5RUJzTThi
            YWVMRFVmblpMbmozbjQxRTRxTWpQOEEKLS0tIDkrWUp0UGhRWUpXck5uK2dSVEhJ
            WEs1YnFJeFVtTUxzSHVBSnZuRUEwZTgKlP+xJSqPZ2Z9IGk22FIrZKstNL7HknWK
            gztpkZ2KO0ze6MdAF2+2oRH0eAF/wECjrNmqHPzbdBBCZ8mdzhY0WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T08:35:38Z"
    mac: ENC[AES256_GCM,data:Zzf7PtmammenS/N4p4eX/14a24QoJH4dNXu7Nv7ghJNlNuk/aPqt8fShmDUZ3ypPcvvFcPdp47XIQRoN81I+IL4lJSYfnwEy2f9tQD+FDVAiW0+sJ/eoNOWUJz4XhavThXRo84bMyRP2nTEDdqdajthrCBArtxS2euz+3zg67fk=,iv:XsE8/FMk/SB4R/xrCNTCidckTT2fEDRtXnS6Pawxu3w=,tag:v0XfvKIqmLV+l7rwm8h73A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
